### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by fudini** [srn/react-webpack-boilerplate#3]
When I run `karma start` I'm getting:
`Uncaught ReferenceError: webpackJsonp is not defined
  at  ...react-webpack-boilerplate/client/components/Index/IndexComponentTest.jsx:1`

**Comment by srn** [comment]
This is because the webpack config is relying on the environment variable `NODE_ENV` to be set to `test`, since we're excluding stuff like the commons bundle and more, which doesn't make sense to have in the tests anyways. If you run `npm test` it will set that environment variable, and the tests will run.

**Comment by fudini** [comment]
Thanks, I got it working.
`npm test` doesn't work on Windows and I had to set `NODE_ENV` manually.
